- name: restart logstash
  service: name=logstash state=restarted

- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: restart kibana
  command: killall -9 node

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

- name: reload systemd
  command: systemctl daemon-reload
