language: ruby
sudo: required
env:
  - CONTAINER_ID=$(mktemp)

rvm:
    - "1.9.3"

services:
  - docker

before_install:
  - sudo apt-get update
  # Pull containers
  - sudo docker pull centos:7
  # Customize containers
  - sudo docker build --rm=true --file=test/Dockerfile.centos --tag=centos:ansible .
  - gem install jls-grok

script:
  - ruby test/test.rb
  # Run container in detached state
  - sudo docker run --detach --privileged --volume="${PWD}":/etc/ansible/lightsiem:ro --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro centos:ansible /usr/lib/systemd/systemd > /tmp/container_id
  # Check syntax of ansible playbook
  - sudo docker exec "$(cat /tmp/container_id)" ansible-playbook  /etc/ansible/lightsiem/lightsiem-install.yml --syntax-check
  # Run ansible playbook
  - sudo docker exec "$(cat /tmp/container_id)" ansible-playbook  /etc/ansible/lightsiem/lightsiem-install.yml
  - sudo docker exec "$(cat /tmp/container_id)" /opt/logstash/bin/logstash -f /etc/logstash/conf.d/ &
  - sleep 60


  - sudo docker exec "$(cat /tmp/container_id)" netstat -lntup
#  - sudo docker exec "$(cat /tmp/container_id)" tail /var/log/logstash/logstash.*
#  - sudo docker exec "$(cat /tmp/container_id)" /etc/init.d/logstash status

#  - sleep 100
#  - sudo docker exec "$(cat /tmp/container_id)" whereis java
#  - sudo docker exec "$(cat /tmp/container_id)" export
  #Logstash Cisco
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lnup | grep "9020"
  #Logstash Ossec
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lnup | grep "9000"
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lntp | grep "9001"
  #Elastcisearch
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lntp | grep "127.0.0.1:9200"
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lntp | grep "127.0.0.1:9300"
  #Kibana
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lntp | grep "5601"
  #Dnsmasq
  - sudo docker exec "$(cat /tmp/container_id)" netstat -lnup | grep "127.0.0.1:53"

  # Clean up
  - sudo docker stop "$(cat /tmp/container_id)"

notifications:
  email:
    on_failure: always
    on_success: change
