- name: Place Elasticsearch repo file
  copy: src=repos/elastico.repo dest=/etc/yum.repos.d/

- name: Import GPG key
  command: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install packages
  yum: name={{item}} state=present
  with_items:
    - elasticsearch-5.1.1
    - java
    - wget
    - epel-release
    - logstash
    - dnsmasq
    - kibana-5.1.1
    - elasticdump
    - openssl
    - psmisc

- name: Add software to autostart to autostart
  command: systemctl enable {{item}}
  with_items:
    - elasticsearch
    - logstash
    - dnsmasq
    - kibana

- name: Place Elasticsearch config file
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
  notify:
        - restart elasticsearch
  tags:
        - configuration

# - name: Install search-guard-ssl
#   command: /usr/share/elasticsearch/bin/plugin install com.floragunn/search-guard-ssl/2.3.4.16
#   tags: configuration security

- name: Check search-guard-5 is installed
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin list | grep search-guard-5
  register: sg_installed

- name: Install search-guard-5
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.1.1-9
  tags: configuration security
  when: sg_installed.stdout != "search-guard-5"


- name: Add netty-tcnative to search-guard plugin
  copy: src=netty-tcnative-1.1.33.Fork13-linux-x86_64.jar dest=/usr/share/elasticsearch/plugins/search-guard-5/
  tags: configuration security

- name: Create ssl folder for searchguard
  file: path=/opt/lightsiem/sg/ state=directory

- name: Place search-guard-ssl pki scripts
  copy: src=example-pki-scripts/ dest=/opt/lightsiem/sg/ mode="o+x"
  tags: configuration security

- name: Create your own Root CA, Generate Keystores, Client node cert
  shell: cd /opt/lightsiem/sg/ && /opt/lightsiem/sg/example.sh
  tags: configuration security

- name: Create folder for ssl certificates
  file: path=/etc/elasticsearch/sg/ state=directory

- name: Copy keystores
  copy: src=/opt/lightsiem/sg/{{item}} dest=/etc/elasticsearch/sg/
  with_items:
        - node-{{ansible_nodename}}-keystore.jks
        - node-{{ansible_nodename}}-keystore.p12
        - truststore.jks
        - admin-keystore.jks
  notify:
        - restart elasticsearch

- name: Flush handlers
  meta: flush_handlers

- name: Copy SG config
  copy: src={{item}} dest=/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/
  with_items:
        - sg_internal_users.yml
        - sg_roles_mapping.yml
        - sg_roles.yml

- name: Add execution right for sgadmin script
  file: path=/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh mode="o+x"

- name: Waight for Elasticsearch
  wait_for: port={{item}} delay=10 connect_timeout=10
  with_items:
      - 9200
      - 9300

- name: Apply sg_config
  shell: /opt/lightsiem/sg/apply_config.sh
  retries: 10
  delay: 1
  notify:
       - restart elasticsearch
       - restart kibana
       - restart logstash
  tags: configuration security


- name: Add dnsmasq config
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.d/lightsiem.conf
  tags:
    - configuration
  notify:
    - restart dnsmasq

- name: Create folder for SG ssl certificates
  file: path=/etc/logstash/ssl/ state=directory

- name: Copy keystores for logstash
  copy: src=/opt/lightsiem/sg/{{item}} dest=/etc/logstash/ssl/
  with_items:
        - node-{{ansible_nodename}}-keystore.jks
        - node-{{ansible_nodename}}-keystore.p12
        - truststore.jks

- name: Add Logstash configs
  copy: src=logstash-conf.d/{{item}} dest=/etc/logstash/conf.d/
  with_items:
    - 20-ossec.conf
    - 30-snort.conf
    - 40-cisco.conf
    - 60-netflow.conf
    - 95-common.conf
    - 98-mail.conf
  tags:
    - configuration
  notify:
    - restart logstash

- name: Add Logstash output config
  template: src=99-output.conf.j2 dest=/etc/logstash/conf.d/99-output.conf
  tags:
    - configuration
  notify:
    - restart logstash

- name: Create patterns directory
  file: path=/opt/lightsiem/patterns state=directory

- name: Place Logstash patterns
  copy: src=logstash-patterns/{{item}} dest=/opt/lightsiem/patterns/
  with_items:
    - cisco.pattern
    - ossec.pattern
    - snort.pattern
    - idmef.pattern
  notify:
    - restart logstash
  tags:
    - configuration

- name: Place Logstash output template
  copy: src=template.json dest=/etc/logstash/
  tags:
    - configuration
  notify:
    - restart logstash

- name: Install email output for logstash
  command: /usr/share/logstash/bin/logstash-plugin install logstash-output-email
  notify:
    - restart logstash

- name: Open ports in firewalld
  firewalld: port={{item}} permanent=true state=enabled
  with_items:
    #kibana server
    - 5601/tcp
    #ossec syslog
    - 9000/udp
    #ossec filebeat
    - 9001/tcp
    #snort filebeat
    - 9010/tcp
    #cisco syslog
    - 9020/udp
    #netflow
    - 9999/udp
  tags:
        - configuration
  notify:
        - restart firewalld
  ignore_errors: yes


# - name: Flush handlers
#   meta: flush_handlers
#
# - name: Waight for Logstash and Elasticsearch
#   wait_for: port={{item}} delay=10 connect_timeout=10
#   with_items:
#       - 9200
#       - 9300
#       - 9001
#       - 9010


# - name: Flush handlers
#   meta: flush_handlers
#
# - name: Waight for Logstash and Elasticsearch
#   wait_for: port={{item}} delay=10 connect_timeout=10
#   with_items:
#       - 9200
#       - 9300

- name: Install searchGuard plugin for Kibana
  command: /usr/share/kibana/bin/kibana-plugin install https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.1.1-alpha/searchguard-kibana-alpha-5.1.1.zip
  notify:
       - restart kibana

- name: Place Kibana 5 config
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml
  tags:
        - configuration
  notify:
       - restart kibana
